apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-backend
  template:
    metadata:
      labels:
        app: library-backend
    spec:
      containers:
        - name: library-backend
          image: your-dockerhub-username/library-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: library-backend-service
spec:
  selector:
    app: library-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
