version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql-container-aplib
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ap-library-db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
