name: Run Unit Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore **/*.sln

      - name: Build solution
        run: dotnet build **/*.sln --configuration Release --no-restore

      - name: Run unit tests with coverage
        run: dotnet test **/*.sln --collect:"XPlat Code Coverage"
